// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: rpc/proto/rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRequest) Reset() {
	*x = ServerRequest{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest) ProtoMessage() {}

func (x *ServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest.ProtoReflect.Descriptor instead.
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ServerRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerReply) Reset() {
	*x = ServerReply{}
	mi := &file_rpc_proto_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply) ProtoMessage() {}

func (x *ServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply.ProtoReflect.Descriptor instead.
func (*ServerReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ServerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_proto_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/proto/rpc.proto\x12\x03rpc\")\n" +
	"\rServerRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\vServerReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2E\n" +
	"\vServerProto\x126\n" +
	"\n" +
	"SendServer\x12\x12.rpc.ServerRequest\x1a\x10.rpc.ServerReply\"\x00(\x01B$Z\"github.com/distninja/distninja/rpcb\x06proto3"

var (
	file_rpc_proto_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rpc_proto_rawDesc), len(file_rpc_proto_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rpc_proto_rawDescData
}

var file_rpc_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_proto_rpc_proto_goTypes = []any{
	(*ServerRequest)(nil), // 0: rpc.ServerRequest
	(*ServerReply)(nil),   // 1: rpc.ServerReply
}
var file_rpc_proto_rpc_proto_depIdxs = []int32{
	0, // 0: rpc.ServerProto.SendServer:input_type -> rpc.ServerRequest
	1, // 1: rpc.ServerProto.SendServer:output_type -> rpc.ServerReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_rpc_proto_init() }
func file_rpc_proto_rpc_proto_init() {
	if File_rpc_proto_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rpc_proto_rawDesc), len(file_rpc_proto_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto_rpc_proto = out.File
	file_rpc_proto_rpc_proto_goTypes = nil
	file_rpc_proto_rpc_proto_depIdxs = nil
}
