---
builds:
  - id: distninja
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: distninja
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/distninja/distninja/cmd.BuildTime={{.Date}} -X github.com/distninja/distninja/cmd.CommitID={{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
