// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server/proto/grpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Admin
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Uptime        string                 `protobuf:"bytes,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

// Build
type CreateBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pool          string                 `protobuf:"bytes,4,opt,name=pool,proto3" json:"pool,omitempty"`
	Inputs        []string               `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []string               `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	ImplicitDeps  []string               `protobuf:"bytes,7,rep,name=implicit_deps,json=implicitDeps,proto3" json:"implicit_deps,omitempty"`
	OrderDeps     []string               `protobuf:"bytes,8,rep,name=order_deps,json=orderDeps,proto3" json:"order_deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildRequest) Reset() {
	*x = CreateBuildRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRequest) ProtoMessage() {}

func (x *CreateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CreateBuildRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *CreateBuildRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *CreateBuildRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *CreateBuildRequest) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *CreateBuildRequest) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *CreateBuildRequest) GetImplicitDeps() []string {
	if x != nil {
		return x.ImplicitDeps
	}
	return nil
}

func (x *CreateBuildRequest) GetOrderDeps() []string {
	if x != nil {
		return x.OrderDeps
	}
	return nil
}

type CreateBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildResponse) Reset() {
	*x = CreateBuildResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildResponse) ProtoMessage() {}

func (x *CreateBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildResponse.ProtoReflect.Descriptor instead.
func (*CreateBuildResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBuildResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateBuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type GetBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetBuildRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuildStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStatsRequest) Reset() {
	*x = BuildStatsRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatsRequest) ProtoMessage() {}

func (x *BuildStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatsRequest.ProtoReflect.Descriptor instead.
func (*BuildStatsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{7}
}

type BuildStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         map[string]int64       `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStatsResponse) Reset() {
	*x = BuildStatsResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatsResponse) ProtoMessage() {}

func (x *BuildStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatsResponse.ProtoReflect.Descriptor instead.
func (*BuildStatsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *BuildStatsResponse) GetStats() map[string]int64 {
	if x != nil {
		return x.Stats
	}
	return nil
}

type BuildOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildOrderRequest) Reset() {
	*x = BuildOrderRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildOrderRequest) ProtoMessage() {}

func (x *BuildOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildOrderRequest.ProtoReflect.Descriptor instead.
func (*BuildOrderRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{9}
}

type BuildOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildOrder    []string               `protobuf:"bytes,1,rep,name=build_order,json=buildOrder,proto3" json:"build_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildOrderResponse) Reset() {
	*x = BuildOrderResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildOrderResponse) ProtoMessage() {}

func (x *BuildOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildOrderResponse.ProtoReflect.Descriptor instead.
func (*BuildOrderResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *BuildOrderResponse) GetBuildOrder() []string {
	if x != nil {
		return x.BuildOrder
	}
	return nil
}

// Rule
type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRuleRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type CreateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleResponse) Reset() {
	*x = CreateRuleResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleResponse) ProtoMessage() {}

func (x *CreateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRuleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRuleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTargetsByRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetsByRuleRequest) Reset() {
	*x = GetTargetsByRuleRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetsByRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetsByRuleRequest) ProtoMessage() {}

func (x *GetTargetsByRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetsByRuleRequest.ProtoReflect.Descriptor instead.
func (*GetTargetsByRuleRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetTargetsByRuleRequest) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

type GetTargetsByRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*NinjaTarget         `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetsByRuleResponse) Reset() {
	*x = GetTargetsByRuleResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetsByRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetsByRuleResponse) ProtoMessage() {}

func (x *GetTargetsByRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetsByRuleResponse.ProtoReflect.Descriptor instead.
func (*GetTargetsByRuleResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetTargetsByRuleResponse) GetTargets() []*NinjaTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Target
type GetAllTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTargetsRequest) Reset() {
	*x = GetAllTargetsRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTargetsRequest) ProtoMessage() {}

func (x *GetAllTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTargetsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTargetsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{16}
}

type GetAllTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*NinjaTarget         `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTargetsResponse) Reset() {
	*x = GetAllTargetsResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTargetsResponse) ProtoMessage() {}

func (x *GetAllTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTargetsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTargetsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllTargetsResponse) GetTargets() []*NinjaTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type GetTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetRequest) Reset() {
	*x = GetTargetRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetRequest) ProtoMessage() {}

func (x *GetTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetRequest.ProtoReflect.Descriptor instead.
func (*GetTargetRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{18}
}

func (x *GetTargetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetTargetDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetDependenciesRequest) Reset() {
	*x = GetTargetDependenciesRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetDependenciesRequest) ProtoMessage() {}

func (x *GetTargetDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetTargetDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{19}
}

func (x *GetTargetDependenciesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetTargetDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*NinjaFile           `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetDependenciesResponse) Reset() {
	*x = GetTargetDependenciesResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetDependenciesResponse) ProtoMessage() {}

func (x *GetTargetDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetTargetDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{20}
}

func (x *GetTargetDependenciesResponse) GetDependencies() []*NinjaFile {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type GetTargetReverseDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetReverseDependenciesRequest) Reset() {
	*x = GetTargetReverseDependenciesRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetReverseDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetReverseDependenciesRequest) ProtoMessage() {}

func (x *GetTargetReverseDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetReverseDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetTargetReverseDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{21}
}

func (x *GetTargetReverseDependenciesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetTargetReverseDependenciesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReverseDependencies []*NinjaTarget         `protobuf:"bytes,1,rep,name=reverse_dependencies,json=reverseDependencies,proto3" json:"reverse_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTargetReverseDependenciesResponse) Reset() {
	*x = GetTargetReverseDependenciesResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetReverseDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetReverseDependenciesResponse) ProtoMessage() {}

func (x *GetTargetReverseDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetReverseDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetTargetReverseDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{22}
}

func (x *GetTargetReverseDependenciesResponse) GetReverseDependencies() []*NinjaTarget {
	if x != nil {
		return x.ReverseDependencies
	}
	return nil
}

type UpdateTargetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTargetStatusRequest) Reset() {
	*x = UpdateTargetStatusRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetStatusRequest) ProtoMessage() {}

func (x *UpdateTargetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTargetStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateTargetStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateTargetStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTargetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTargetStatusResponse) Reset() {
	*x = UpdateTargetStatusResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetStatusResponse) ProtoMessage() {}

func (x *UpdateTargetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTargetStatusResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateTargetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Analysis
type FindCyclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCyclesRequest) Reset() {
	*x = FindCyclesRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCyclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCyclesRequest) ProtoMessage() {}

func (x *FindCyclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCyclesRequest.ProtoReflect.Descriptor instead.
func (*FindCyclesRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{25}
}

type FindCyclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cycles        []*Cycle               `protobuf:"bytes,1,rep,name=cycles,proto3" json:"cycles,omitempty"`
	CycleCount    int32                  `protobuf:"varint,2,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCyclesResponse) Reset() {
	*x = FindCyclesResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCyclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCyclesResponse) ProtoMessage() {}

func (x *FindCyclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCyclesResponse.ProtoReflect.Descriptor instead.
func (*FindCyclesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{26}
}

func (x *FindCyclesResponse) GetCycles() []*Cycle {
	if x != nil {
		return x.Cycles
	}
	return nil
}

func (x *FindCyclesResponse) GetCycleCount() int32 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

type Cycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cycle) Reset() {
	*x = Cycle{}
	mi := &file_server_proto_grpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cycle) ProtoMessage() {}

func (x *Cycle) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cycle.ProtoReflect.Descriptor instead.
func (*Cycle) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{27}
}

func (x *Cycle) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Debug
type DebugQuadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugQuadsRequest) Reset() {
	*x = DebugQuadsRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugQuadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugQuadsRequest) ProtoMessage() {}

func (x *DebugQuadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugQuadsRequest.ProtoReflect.Descriptor instead.
func (*DebugQuadsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{28}
}

func (x *DebugQuadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DebugQuadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugQuadsResponse) Reset() {
	*x = DebugQuadsResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugQuadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugQuadsResponse) ProtoMessage() {}

func (x *DebugQuadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugQuadsResponse.ProtoReflect.Descriptor instead.
func (*DebugQuadsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{29}
}

func (x *DebugQuadsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DebugQuadsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Load
type LoadNinjaFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadNinjaFileRequest) Reset() {
	*x = LoadNinjaFileRequest{}
	mi := &file_server_proto_grpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadNinjaFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadNinjaFileRequest) ProtoMessage() {}

func (x *LoadNinjaFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadNinjaFileRequest.ProtoReflect.Descriptor instead.
func (*LoadNinjaFileRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{30}
}

func (x *LoadNinjaFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadNinjaFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LoadNinjaFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         map[string]int64       `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BuildTime     string                 `protobuf:"bytes,4,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadNinjaFileResponse) Reset() {
	*x = LoadNinjaFileResponse{}
	mi := &file_server_proto_grpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadNinjaFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadNinjaFileResponse) ProtoMessage() {}

func (x *LoadNinjaFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadNinjaFileResponse.ProtoReflect.Descriptor instead.
func (*LoadNinjaFileResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{31}
}

func (x *LoadNinjaFileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoadNinjaFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadNinjaFileResponse) GetStats() map[string]int64 {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *LoadNinjaFileResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

// Ninja
type NinjaBuild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BuildId       string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Rule          string                 `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Variables     string                 `protobuf:"bytes,5,opt,name=variables,proto3" json:"variables,omitempty"`
	Pool          string                 `protobuf:"bytes,6,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NinjaBuild) Reset() {
	*x = NinjaBuild{}
	mi := &file_server_proto_grpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NinjaBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NinjaBuild) ProtoMessage() {}

func (x *NinjaBuild) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NinjaBuild.ProtoReflect.Descriptor instead.
func (*NinjaBuild) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{32}
}

func (x *NinjaBuild) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NinjaBuild) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NinjaBuild) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *NinjaBuild) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *NinjaBuild) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

func (x *NinjaBuild) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

type NinjaFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NinjaFile) Reset() {
	*x = NinjaFile{}
	mi := &file_server_proto_grpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NinjaFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NinjaFile) ProtoMessage() {}

func (x *NinjaFile) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NinjaFile.ProtoReflect.Descriptor instead.
func (*NinjaFile) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{33}
}

func (x *NinjaFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NinjaFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NinjaFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NinjaFile) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type NinjaRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Variables     string                 `protobuf:"bytes,6,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NinjaRule) Reset() {
	*x = NinjaRule{}
	mi := &file_server_proto_grpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NinjaRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NinjaRule) ProtoMessage() {}

func (x *NinjaRule) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NinjaRule.ProtoReflect.Descriptor instead.
func (*NinjaRule) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{34}
}

func (x *NinjaRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NinjaRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NinjaRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NinjaRule) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *NinjaRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NinjaRule) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

type NinjaTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Build         string                 `protobuf:"bytes,6,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NinjaTarget) Reset() {
	*x = NinjaTarget{}
	mi := &file_server_proto_grpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NinjaTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NinjaTarget) ProtoMessage() {}

func (x *NinjaTarget) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_grpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NinjaTarget.ProtoReflect.Descriptor instead.
func (*NinjaTarget) Descriptor() ([]byte, []int) {
	return file_server_proto_grpc_proto_rawDescGZIP(), []int{35}
}

func (x *NinjaTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NinjaTarget) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NinjaTarget) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NinjaTarget) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NinjaTarget) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *NinjaTarget) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

var File_server_proto_grpc_proto protoreflect.FileDescriptor

const file_server_proto_grpc_proto_rawDesc = "" +
	"\n" +
	"\x17server/proto/grpc.proto\x12\tdistninja\"\x0f\n" +
	"\rHealthRequest\"F\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\x0f\n" +
	"\rStatusRequest\"B\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\tR\x06uptime\"\xd7\x02\n" +
	"\x12CreateBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12J\n" +
	"\tvariables\x18\x03 \x03(\v2,.distninja.CreateBuildRequest.VariablesEntryR\tvariables\x12\x12\n" +
	"\x04pool\x18\x04 \x01(\tR\x04pool\x12\x16\n" +
	"\x06inputs\x18\x05 \x03(\tR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\x06 \x03(\tR\aoutputs\x12#\n" +
	"\rimplicit_deps\x18\a \x03(\tR\fimplicitDeps\x12\x1d\n" +
	"\n" +
	"order_deps\x18\b \x03(\tR\torderDeps\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13CreateBuildResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\"!\n" +
	"\x0fGetBuildRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11BuildStatsRequest\"\x8e\x01\n" +
	"\x12BuildStatsResponse\x12>\n" +
	"\x05stats\x18\x01 \x03(\v2(.distninja.BuildStatsResponse.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x13\n" +
	"\x11BuildOrderRequest\"5\n" +
	"\x12BuildOrderResponse\x12\x1f\n" +
	"\vbuild_order\x18\x01 \x03(\tR\n" +
	"buildOrder\"\xec\x01\n" +
	"\x11CreateRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12I\n" +
	"\tvariables\x18\x04 \x03(\v2+.distninja.CreateRuleRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x12CreateRuleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"$\n" +
	"\x0eGetRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x17GetTargetsByRuleRequest\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\"L\n" +
	"\x18GetTargetsByRuleResponse\x120\n" +
	"\atargets\x18\x01 \x03(\v2\x16.distninja.NinjaTargetR\atargets\"\x16\n" +
	"\x14GetAllTargetsRequest\"I\n" +
	"\x15GetAllTargetsResponse\x120\n" +
	"\atargets\x18\x01 \x03(\v2\x16.distninja.NinjaTargetR\atargets\"&\n" +
	"\x10GetTargetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"2\n" +
	"\x1cGetTargetDependenciesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Y\n" +
	"\x1dGetTargetDependenciesResponse\x128\n" +
	"\fdependencies\x18\x01 \x03(\v2\x14.distninja.NinjaFileR\fdependencies\"9\n" +
	"#GetTargetReverseDependenciesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"q\n" +
	"$GetTargetReverseDependenciesResponse\x12I\n" +
	"\x14reverse_dependencies\x18\x01 \x03(\v2\x16.distninja.NinjaTargetR\x13reverseDependencies\"G\n" +
	"\x19UpdateTargetStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"4\n" +
	"\x1aUpdateTargetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x13\n" +
	"\x11FindCyclesRequest\"_\n" +
	"\x12FindCyclesResponse\x12(\n" +
	"\x06cycles\x18\x01 \x03(\v2\x10.distninja.CycleR\x06cycles\x12\x1f\n" +
	"\vcycle_count\x18\x02 \x01(\x05R\n" +
	"cycleCount\"\x1d\n" +
	"\x05Cycle\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\")\n" +
	"\x11DebugQuadsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"D\n" +
	"\x12DebugQuadsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x14LoadNinjaFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xe5\x01\n" +
	"\x15LoadNinjaFileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x05stats\x18\x03 \x03(\v2+.distninja.LoadNinjaFileResponse.StatsEntryR\x05stats\x12\x1d\n" +
	"\n" +
	"build_time\x18\x04 \x01(\tR\tbuildTime\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x91\x01\n" +
	"\n" +
	"NinjaBuild\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12\x12\n" +
	"\x04rule\x18\x04 \x01(\tR\x04rule\x12\x1c\n" +
	"\tvariables\x18\x05 \x01(\tR\tvariables\x12\x12\n" +
	"\x04pool\x18\x06 \x01(\tR\x04pool\"`\n" +
	"\tNinjaFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"\x9d\x01\n" +
	"\tNinjaRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tvariables\x18\x06 \x01(\tR\tvariables\"\x87\x01\n" +
	"\vNinjaTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x14\n" +
	"\x05build\x18\x06 \x01(\tR\x05build2\xed\n" +
	"\n" +
	"\x10DistNinjaService\x12=\n" +
	"\x06Health\x12\x18.distninja.HealthRequest\x1a\x19.distninja.HealthResponse\x12=\n" +
	"\x06Status\x12\x18.distninja.StatusRequest\x1a\x19.distninja.StatusResponse\x12L\n" +
	"\vCreateBuild\x12\x1d.distninja.CreateBuildRequest\x1a\x1e.distninja.CreateBuildResponse\x12=\n" +
	"\bGetBuild\x12\x1a.distninja.GetBuildRequest\x1a\x15.distninja.NinjaBuild\x12L\n" +
	"\rGetBuildStats\x12\x1c.distninja.BuildStatsRequest\x1a\x1d.distninja.BuildStatsResponse\x12L\n" +
	"\rGetBuildOrder\x12\x1c.distninja.BuildOrderRequest\x1a\x1d.distninja.BuildOrderResponse\x12I\n" +
	"\n" +
	"CreateRule\x12\x1c.distninja.CreateRuleRequest\x1a\x1d.distninja.CreateRuleResponse\x12:\n" +
	"\aGetRule\x12\x19.distninja.GetRuleRequest\x1a\x14.distninja.NinjaRule\x12[\n" +
	"\x10GetTargetsByRule\x12\".distninja.GetTargetsByRuleRequest\x1a#.distninja.GetTargetsByRuleResponse\x12R\n" +
	"\rGetAllTargets\x12\x1f.distninja.GetAllTargetsRequest\x1a .distninja.GetAllTargetsResponse\x12@\n" +
	"\tGetTarget\x12\x1b.distninja.GetTargetRequest\x1a\x16.distninja.NinjaTarget\x12j\n" +
	"\x15GetTargetDependencies\x12'.distninja.GetTargetDependenciesRequest\x1a(.distninja.GetTargetDependenciesResponse\x12\x7f\n" +
	"\x1cGetTargetReverseDependencies\x12..distninja.GetTargetReverseDependenciesRequest\x1a/.distninja.GetTargetReverseDependenciesResponse\x12a\n" +
	"\x12UpdateTargetStatus\x12$.distninja.UpdateTargetStatusRequest\x1a%.distninja.UpdateTargetStatusResponse\x12I\n" +
	"\n" +
	"FindCycles\x12\x1c.distninja.FindCyclesRequest\x1a\x1d.distninja.FindCyclesResponse\x12I\n" +
	"\n" +
	"DebugQuads\x12\x1c.distninja.DebugQuadsRequest\x1a\x1d.distninja.DebugQuadsResponse\x12R\n" +
	"\rLoadNinjaFile\x12\x1f.distninja.LoadNinjaFileRequest\x1a .distninja.LoadNinjaFileResponseB3Z1github.com/distninja/distninja/server/proto;protob\x06proto3"

var (
	file_server_proto_grpc_proto_rawDescOnce sync.Once
	file_server_proto_grpc_proto_rawDescData []byte
)

func file_server_proto_grpc_proto_rawDescGZIP() []byte {
	file_server_proto_grpc_proto_rawDescOnce.Do(func() {
		file_server_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_grpc_proto_rawDesc), len(file_server_proto_grpc_proto_rawDesc)))
	})
	return file_server_proto_grpc_proto_rawDescData
}

var file_server_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_server_proto_grpc_proto_goTypes = []any{
	(*HealthRequest)(nil),                        // 0: distninja.HealthRequest
	(*HealthResponse)(nil),                       // 1: distninja.HealthResponse
	(*StatusRequest)(nil),                        // 2: distninja.StatusRequest
	(*StatusResponse)(nil),                       // 3: distninja.StatusResponse
	(*CreateBuildRequest)(nil),                   // 4: distninja.CreateBuildRequest
	(*CreateBuildResponse)(nil),                  // 5: distninja.CreateBuildResponse
	(*GetBuildRequest)(nil),                      // 6: distninja.GetBuildRequest
	(*BuildStatsRequest)(nil),                    // 7: distninja.BuildStatsRequest
	(*BuildStatsResponse)(nil),                   // 8: distninja.BuildStatsResponse
	(*BuildOrderRequest)(nil),                    // 9: distninja.BuildOrderRequest
	(*BuildOrderResponse)(nil),                   // 10: distninja.BuildOrderResponse
	(*CreateRuleRequest)(nil),                    // 11: distninja.CreateRuleRequest
	(*CreateRuleResponse)(nil),                   // 12: distninja.CreateRuleResponse
	(*GetRuleRequest)(nil),                       // 13: distninja.GetRuleRequest
	(*GetTargetsByRuleRequest)(nil),              // 14: distninja.GetTargetsByRuleRequest
	(*GetTargetsByRuleResponse)(nil),             // 15: distninja.GetTargetsByRuleResponse
	(*GetAllTargetsRequest)(nil),                 // 16: distninja.GetAllTargetsRequest
	(*GetAllTargetsResponse)(nil),                // 17: distninja.GetAllTargetsResponse
	(*GetTargetRequest)(nil),                     // 18: distninja.GetTargetRequest
	(*GetTargetDependenciesRequest)(nil),         // 19: distninja.GetTargetDependenciesRequest
	(*GetTargetDependenciesResponse)(nil),        // 20: distninja.GetTargetDependenciesResponse
	(*GetTargetReverseDependenciesRequest)(nil),  // 21: distninja.GetTargetReverseDependenciesRequest
	(*GetTargetReverseDependenciesResponse)(nil), // 22: distninja.GetTargetReverseDependenciesResponse
	(*UpdateTargetStatusRequest)(nil),            // 23: distninja.UpdateTargetStatusRequest
	(*UpdateTargetStatusResponse)(nil),           // 24: distninja.UpdateTargetStatusResponse
	(*FindCyclesRequest)(nil),                    // 25: distninja.FindCyclesRequest
	(*FindCyclesResponse)(nil),                   // 26: distninja.FindCyclesResponse
	(*Cycle)(nil),                                // 27: distninja.Cycle
	(*DebugQuadsRequest)(nil),                    // 28: distninja.DebugQuadsRequest
	(*DebugQuadsResponse)(nil),                   // 29: distninja.DebugQuadsResponse
	(*LoadNinjaFileRequest)(nil),                 // 30: distninja.LoadNinjaFileRequest
	(*LoadNinjaFileResponse)(nil),                // 31: distninja.LoadNinjaFileResponse
	(*NinjaBuild)(nil),                           // 32: distninja.NinjaBuild
	(*NinjaFile)(nil),                            // 33: distninja.NinjaFile
	(*NinjaRule)(nil),                            // 34: distninja.NinjaRule
	(*NinjaTarget)(nil),                          // 35: distninja.NinjaTarget
	nil,                                          // 36: distninja.CreateBuildRequest.VariablesEntry
	nil,                                          // 37: distninja.BuildStatsResponse.StatsEntry
	nil,                                          // 38: distninja.CreateRuleRequest.VariablesEntry
	nil,                                          // 39: distninja.LoadNinjaFileResponse.StatsEntry
}
var file_server_proto_grpc_proto_depIdxs = []int32{
	36, // 0: distninja.CreateBuildRequest.variables:type_name -> distninja.CreateBuildRequest.VariablesEntry
	37, // 1: distninja.BuildStatsResponse.stats:type_name -> distninja.BuildStatsResponse.StatsEntry
	38, // 2: distninja.CreateRuleRequest.variables:type_name -> distninja.CreateRuleRequest.VariablesEntry
	35, // 3: distninja.GetTargetsByRuleResponse.targets:type_name -> distninja.NinjaTarget
	35, // 4: distninja.GetAllTargetsResponse.targets:type_name -> distninja.NinjaTarget
	33, // 5: distninja.GetTargetDependenciesResponse.dependencies:type_name -> distninja.NinjaFile
	35, // 6: distninja.GetTargetReverseDependenciesResponse.reverse_dependencies:type_name -> distninja.NinjaTarget
	27, // 7: distninja.FindCyclesResponse.cycles:type_name -> distninja.Cycle
	39, // 8: distninja.LoadNinjaFileResponse.stats:type_name -> distninja.LoadNinjaFileResponse.StatsEntry
	0,  // 9: distninja.DistNinjaService.Health:input_type -> distninja.HealthRequest
	2,  // 10: distninja.DistNinjaService.Status:input_type -> distninja.StatusRequest
	4,  // 11: distninja.DistNinjaService.CreateBuild:input_type -> distninja.CreateBuildRequest
	6,  // 12: distninja.DistNinjaService.GetBuild:input_type -> distninja.GetBuildRequest
	7,  // 13: distninja.DistNinjaService.GetBuildStats:input_type -> distninja.BuildStatsRequest
	9,  // 14: distninja.DistNinjaService.GetBuildOrder:input_type -> distninja.BuildOrderRequest
	11, // 15: distninja.DistNinjaService.CreateRule:input_type -> distninja.CreateRuleRequest
	13, // 16: distninja.DistNinjaService.GetRule:input_type -> distninja.GetRuleRequest
	14, // 17: distninja.DistNinjaService.GetTargetsByRule:input_type -> distninja.GetTargetsByRuleRequest
	16, // 18: distninja.DistNinjaService.GetAllTargets:input_type -> distninja.GetAllTargetsRequest
	18, // 19: distninja.DistNinjaService.GetTarget:input_type -> distninja.GetTargetRequest
	19, // 20: distninja.DistNinjaService.GetTargetDependencies:input_type -> distninja.GetTargetDependenciesRequest
	21, // 21: distninja.DistNinjaService.GetTargetReverseDependencies:input_type -> distninja.GetTargetReverseDependenciesRequest
	23, // 22: distninja.DistNinjaService.UpdateTargetStatus:input_type -> distninja.UpdateTargetStatusRequest
	25, // 23: distninja.DistNinjaService.FindCycles:input_type -> distninja.FindCyclesRequest
	28, // 24: distninja.DistNinjaService.DebugQuads:input_type -> distninja.DebugQuadsRequest
	30, // 25: distninja.DistNinjaService.LoadNinjaFile:input_type -> distninja.LoadNinjaFileRequest
	1,  // 26: distninja.DistNinjaService.Health:output_type -> distninja.HealthResponse
	3,  // 27: distninja.DistNinjaService.Status:output_type -> distninja.StatusResponse
	5,  // 28: distninja.DistNinjaService.CreateBuild:output_type -> distninja.CreateBuildResponse
	32, // 29: distninja.DistNinjaService.GetBuild:output_type -> distninja.NinjaBuild
	8,  // 30: distninja.DistNinjaService.GetBuildStats:output_type -> distninja.BuildStatsResponse
	10, // 31: distninja.DistNinjaService.GetBuildOrder:output_type -> distninja.BuildOrderResponse
	12, // 32: distninja.DistNinjaService.CreateRule:output_type -> distninja.CreateRuleResponse
	34, // 33: distninja.DistNinjaService.GetRule:output_type -> distninja.NinjaRule
	15, // 34: distninja.DistNinjaService.GetTargetsByRule:output_type -> distninja.GetTargetsByRuleResponse
	17, // 35: distninja.DistNinjaService.GetAllTargets:output_type -> distninja.GetAllTargetsResponse
	35, // 36: distninja.DistNinjaService.GetTarget:output_type -> distninja.NinjaTarget
	20, // 37: distninja.DistNinjaService.GetTargetDependencies:output_type -> distninja.GetTargetDependenciesResponse
	22, // 38: distninja.DistNinjaService.GetTargetReverseDependencies:output_type -> distninja.GetTargetReverseDependenciesResponse
	24, // 39: distninja.DistNinjaService.UpdateTargetStatus:output_type -> distninja.UpdateTargetStatusResponse
	26, // 40: distninja.DistNinjaService.FindCycles:output_type -> distninja.FindCyclesResponse
	29, // 41: distninja.DistNinjaService.DebugQuads:output_type -> distninja.DebugQuadsResponse
	31, // 42: distninja.DistNinjaService.LoadNinjaFile:output_type -> distninja.LoadNinjaFileResponse
	26, // [26:43] is the sub-list for method output_type
	9,  // [9:26] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_server_proto_grpc_proto_init() }
func file_server_proto_grpc_proto_init() {
	if File_server_proto_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_grpc_proto_rawDesc), len(file_server_proto_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_grpc_proto_goTypes,
		DependencyIndexes: file_server_proto_grpc_proto_depIdxs,
		MessageInfos:      file_server_proto_grpc_proto_msgTypes,
	}.Build()
	File_server_proto_grpc_proto = out.File
	file_server_proto_grpc_proto_goTypes = nil
	file_server_proto_grpc_proto_depIdxs = nil
}
